### ISSUE TITLE
Local Notifications not working in iOS8

### ISSUE THREAD

**Issue by mawarnes** [benbahrenburg/LocalNotify#15]
notifications for me have not been working in iOS8, sorry to be a bit vague at this point but have you had any issues with iOS8 and titanium 3.5+ SDK

**Comment by benbahrenburg** [comment]
You will need to provide more details.
If you are experiencing the following, I am not able to create notifications, I am not able to have them run.  These most likely mean you are (1) Not using the Ti SDK functions (2) Have not used the Ti SDK functions and requested permissions. These are are now required for iOS 8.

Here is a link to the reference for the above http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.App.iOS-method-registerUserNotificationSettings

Otherwise, you will need to provide more details.

**Comment by bjanaszek** [comment]
Ben, based on your comment, does that mean in order to use local notification on iOS 8 you *cannot* use this module (that is, you must use the Ti API)?

**Comment by benbahrenburg** [comment]
@bjanaszek you want to use the Ti API to create, and this module to Query

**Comment by bjanaszek** [comment]
@benbahrenburg Thanks.
